### ISSUE TITLE
Add WikiPathways

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ComPath#3]

**Comment by cthoyt** [comment]
If i recall correctly, Christian and andrej wrote some code to grab the gene sets from wiki pathways. Perhaps we could salvage some of that code and spin up a proper bio2bel wikipathways repo

**Comment by ddomingof** [comment]
http://data.wikipathways.org/current/gmt/wikipathways-20180110-gmt-Homo_sapiens.gmt
